name: Playwright Tests

on:
    deployment_status: #changed by me
jobs:
  test:
    # added by me -> if
    if: github.event.deployment_status.state == 'success' 
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests against ${{ github.event.deployment_status.target_url }} #added by me
        run: pnpm exec playwright test
        env:
          PUBLIC_ROOT_URL : ${{ github.event.deployment_status.target_url }} #added by me
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  # if : github.event.deployment_status.state == 'success'
